"""Add Soft Deletion

Revision ID: 2399c50496f7
Revises: 93d6649210e1
Create Date: 2022-06-05 20:40:27.591102

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2399c50496f7'
down_revision = '93d6649210e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bellschedules', sa.Column('soft_deleted', sa.Boolean(), nullable=False, default=False))
    op.add_column('schools', sa.Column('soft_deleted', sa.Boolean(), nullable=False, default=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schools', 'soft_deleted')
    op.drop_column('bellschedules', 'soft_deleted')
    # ### end Alembic commands ###
