"""Initial migration.

Revision ID: 93d6649210e1
Revises: 
Create Date: 2022-06-05 20:34:41.432858

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '93d6649210e1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bellscheduledates', 'creation_date',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.drop_constraint('bellscheduledates_FK', 'bellscheduledates', type_='foreignkey')
    op.drop_column('bellscheduledates', 'school_id')
    op.alter_column('bellschedulemeetingtimes', 'creation_date',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.drop_constraint('bellschedulemeetingtimes_FK', 'bellschedulemeetingtimes', type_='foreignkey')
    op.drop_column('bellschedulemeetingtimes', 'school_id')
    op.alter_column('bellschedules', 'bell_schedule_name',
               existing_type=mysql.VARCHAR(charset='latin1', length=60),
               nullable=True)
    op.alter_column('bellschedules', 'creation_date',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('bellschedules', 'last_modified',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('schools', 'owner_id',
               existing_type=mysql.VARCHAR(length=35),
               nullable=True)
    op.alter_column('schools', 'school_name',
               existing_type=mysql.VARCHAR(charset='latin1', length=75),
               nullable=True)
    op.alter_column('schools', 'creation_date',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('schools', 'last_modified',
               existing_type=mysql.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('schools', 'last_modified',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('schools', 'creation_date',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('schools', 'school_name',
               existing_type=mysql.VARCHAR(charset='latin1', length=75),
               nullable=False)
    op.alter_column('schools', 'owner_id',
               existing_type=mysql.VARCHAR(length=35),
               nullable=False)
    op.alter_column('bellschedules', 'last_modified',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('bellschedules', 'creation_date',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('bellschedules', 'bell_schedule_name',
               existing_type=mysql.VARCHAR(charset='latin1', length=60),
               nullable=False)
    op.add_column('bellschedulemeetingtimes', sa.Column('school_id', sa.BINARY(length=16), nullable=False))
    op.create_foreign_key('bellschedulemeetingtimes_FK', 'bellschedulemeetingtimes', 'schools', ['school_id'], ['school_id'])
    op.alter_column('bellschedulemeetingtimes', 'creation_date',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.add_column('bellscheduledates', sa.Column('school_id', sa.BINARY(length=16), nullable=False))
    op.create_foreign_key('bellscheduledates_FK', 'bellscheduledates', 'schools', ['school_id'], ['school_id'])
    op.alter_column('bellscheduledates', 'creation_date',
               existing_type=mysql.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###
